config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books
  root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_many :books
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :find_book, only: [:show,:edit, :update, :destroy]
	def index
		@books = Book.all.order("created_at DESC")
	end
	def new
		@book = current_user.books.build
	end

	def create
		@book = current_user.books.build(book_params)
		if @book.save
			redirect_to root_path
		else render 'new'
		end
	end

	def show
	end

	def edit
	end

	def update
		if @book.update(book_params)
			redirect_to book_path
		else render 'edit'
		end
	end

	def destroy
		 @book.delete
			redirect_to root_path
		 render 'show'
		
	end

private

def book_params
	params.require(:book).permit(:title, :desc, :author)

end
def find_book
	@book = Book.find(params[:id])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book do |f| %>
  <%= f.input :title ,label: "Book_Title"%>
  <%= f.input :desc, label: "Description" %>
  <%= f.input :author, label: "Author" %>
  <%= f.button :submit %>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>
<%= render 'form'%>

app/views/books/index.html.erb
<% @books.each do |book|%>
<h1><%=link_to book.title, book_path(book) %></h1>
<% end -%>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

app/views/books/show.html.erb
<h1><%=  @book.title  %></h1>
<h3><%= @book.author %></h3>
<p><%= @book.desc %></p>
<%= link_to "Back" , root_path %>


<%if user_signed_in?%>
	<% if @book.user_id == current_user.id%>

	<%= link_to "Edit" , edit_book_path %>
	<%= link_to "Destroy", book_path, method: :DELETE, data: {confirm: "are you sure"}%>
	<% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookReview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Book Review", root_path , class: "navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
      	<% if user_signed_in? %>
      	<li><%= link_to "Add Book" , new_book_path,class: "navbar-brand"%></li>
      	<% end -%>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        
      <% if user_signed_in? %>
        <li><%= link_to "Setting",  edit_user_registration_path,class: "navbar-brand"%></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete,class: "navbar-brand"%></li>
      <%else%>
       	<li><%= link_to "Sign in",  new_user_session_path, class: "navbar-brand"%></li>
		<li><%= link_to "Sign up", new_user_registration_path, class: "navbar-brand"%></li>
      <%end%>

        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
	   <p class="notice"><%= notice %></p>
	   <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>